<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>OidcMock.Host</RootNamespace>
    <UserSecretsId>oidc-mock-host</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\OidcMock.Core\OidcMock.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\config\*.json" Link="config\%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="OidcMock.IntegrationTests" />
  </ItemGroup>

</Project>
